srping:
datasource:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /**
  resources:
    static-locations: "classpath:/META-INF/resources/,classpath:/resources/,\
                         classpath:/static/,classpath:/public/,file:${web.upload-path}"
wechat:
  mpAppId: wxa85afca0e14f8d29
  mpAppSecret: 47fe2e42cf97ba2ef5060db7136362ef

web:
  upload-path: "D:/develep_uploadfile/"

mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - tk.mybatis.springboot.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

