srping:
datasource:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=UTF-8&useSSL=false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
